# Generated by Django 4.2.23 on 2025-08-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
