# Generated by Django 4.2.23 on 2025-12-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_child_class_name_alter_child_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
    ]
